version: '3'
services:
    app1:
        image: ianwijaya/hackazon
        hostname: app1
        ports:
        - "8081:80"
    app2:
        image: ianwijaya/hackazon
        hostname: app2
        ports:
        - "8082:80"
    approtect:
        image: app-protect:latest
        volumes:
            - ./custom_log_format.json:/etc/nginx/custom_log_format.json
            - ./labpolicy.json:/etc/nginx/labpolicy.json
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx-repo.crt:/etc/ssl/nginx/nginx-repo.crt
            - ./nginx-repo.key:/etc/ssl/nginx/nginx-repo.key
        ports:
            - "80:80"
